### ISSUE TITLE
Lua 5.1

### ISSUE THREAD

**Issue by CertHaramas** [KritzelKratzel/OneLuaPro#1]
Hello Kritzel,
is it possible to build the OneLuaPro for Lua 5.1, and make Win32 builds?
– I'm asking mainly as I have some libs just for Lua 5.1 (namely XML reader/writer, Excel .xls reader and WxWidgets).
Best regards,
Lukas

**Comment by KritzelKratzel** [comment]
@CertHaramas: Support for older Lua versions is currently not in my focus. In fact, OneLuaPro shall be aligned to the respectively newest Lua version available. However, as you have mentioned `wxWidgets`, the next release will include `wxWidgets` as well as `ZeroBraneStudio` tailored for OneLuaPro. Here is a preview of a debugging sesstion:

![image](https://github.com/user-attachments/assets/774db9ea-7815-46eb-80bc-28910ddebef3)


Are those XML reader/writer, Excel .xls reader libs tied to Lua 5.1 exclusively?
